// Generated by https://quicktype.io

export interface LoginResponse {
	ok:    boolean;
	msg:   string;
	token: string;
	user:  User;
}

export interface LoginData {
	email: string;
	password: string;
}

export interface User {
	firstName: string;
	lastName:  string;
	email:     string;
	password:  string;
	username:  string;
	role:      string;
	id:        string;
}

