// Generated by https://quicktype.io

export interface LoginResponse {
	ok:    boolean;
	msg:   string;
	token: string;
	user:  User;
}

export interface LoginData {
	email: string;
	password: string;
}

export interface User {
	firstName: string;
	lastName:  string;
	email:     string;
	password:  string;
	username:  string;
	role:      string;
	id:        string;
	img?:      string;
}

// Generated by https://quicktype.io

export interface ProductsResponse {
	total:    number;
	products: Product[];
}

export interface Product {
	name:      string;
	price:     number;
	units:     number;
	categorie: Categorie;
	user:      UserProduct;
	available: boolean;
	img:       string;
	id:        string;
}

export interface Categorie {
	_id:  string;
	name: string;
}

export interface UserProduct {
	_id:      string;
	username: string;
}



// Generated by https://quicktype.io

export interface UpdateUserResponse {
	userUpdated: User;
}


export interface RegisterData {
	firstName: string;
	lastName: string;
	username: string;
	email: string;
	password: string;
}

// Generated by https://quicktype.io

export interface RegisterResponse {
	ok:      boolean;
	newUser: NewUser;
}

export interface NewUser {
	firstName: string;
	lastName:  string;
	email:     string;
	password:  string;
	username:  string;
	role:      string;
	id:        string;
}
